namespace MediCon.Infrastructure.Repository.Operators;

internal class OperatorProcedureNames
{
    public const string GET_CMP_OPERATORINFO = "CMP_DEFINATION.GET_CMP_OPERATORINFO";
    public const string GET_CMP_OPERATORINFO_BY_ID = "CMP_DEFINATION.GET_CMP_OPERATORINFO_BY_ID";
    public const string INSERT_CMP_OPERATORINFO = "CMP_DEFINATION.INSERT_CMP_OPERATORINFO";
    public const string UPDATE_CMP_OPERATORINFO = "CMP_DEFINATION.UPDATE_CMP_OPERATORINFO";
    public const string DELETE_CMP_OPERATORINFO = "CMP_DEFINATION.DELETE_CMP_OPERATORINFO";
}